### PR TITLE
Better means and medians

### PR DESCRIPTION
**Pull request by otfrom**
And a bit of a tweak on a function name to make it clearer.

### CODE REVIEW

**Review by seb231 — COMMENTED** [review]
Code changes fine, not sure I follow what makes he means and medians "better"?

**Review by seb231 — CHANGES_REQUESTED** [review]
Code changes fine, not sure I follow what makes the means and medians "better"?

**Comment by otfrom** [comment]
@seb231 I'm adding the history on to every simulation now, rather than having it as a separate fake simulation that doesn't overlap with the projections. This means + using `tc/complete` means that all medians and means should have the same number of simulations producing their numbers, meaning means can be added and medians/25%/5%/min will show 0 when appropriate.

**Comment by seb231** [comment]
Can you show me where you're doing this?

**Comment by otfrom** [comment]
@seb231 https://github.com/MastodonC/witan.send.adroddiad/pull/30/files#diff-c34e933f3547a585276c1feaa8d87f5b9a274b7e821cfbd5194fd791d6960d9fL91-L98 is the change to how the history and simulation are handled.

**Review by seb231 — APPROVED** [review]

**Pull request merged**
